services:
  db:
    image: bitnami/postgresql:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: development
    ports:
      - "5432:5432"
    volumes:
      - ./development:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    container_name: payment-microservice
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      PAYMENT_SERVICE_PORT: "8001"
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://root:root@auth-db:5432/development?schema=public"
      PAYMENT_SERVICE_URL: "http://microservice:8001/process-payment"
    depends_on:
      db:
        condition: service_healthy