services:
db:
  image: bitnami/postgresql:latest
  container_name: auth-db
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: development
  ports:
    - "5432:5432"
  volumes:
    - ./development:/var/lib/postgresql/data
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
    interval: 10s
    timeout: 5s
    retries: 5