-- Sistema de Pagos - Bootstrap PostgreSQL
--
-- Alternativa para crear una base nueva sin ejecutar las migraciones de Prisma.
-- Debe mantenerse sincronizado con api/prisma/schema.prisma. Este archivo no
-- elimina objetos existentes ni debe utilizarse como mecanismo de migración.

BEGIN;

CREATE TABLE usuarios (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(150) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    telefono    VARCHAR(50),
    direccion   TEXT,
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT usuarios_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT usuarios_email_no_vacio CHECK (btrim(email) <> ''),
    CONSTRAINT usuarios_email_unique UNIQUE (email)
);

CREATE TABLE tarjetas (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INTEGER NOT NULL,
    alias       VARCHAR(100),
    brand       VARCHAR(50),
    last4       CHAR(4) NOT NULL,
    exp_month   INTEGER NOT NULL,
    exp_year    INTEGER NOT NULL,
    token       VARCHAR(255),
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT tarjetas_usuario_fkey
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT tarjetas_id_usuario_unique UNIQUE (id, usuario_id),
    CONSTRAINT tarjetas_last4_formato CHECK (last4 ~ '^[0-9]{4}$'),
    CONSTRAINT tarjetas_exp_month_rango CHECK (exp_month BETWEEN 1 AND 12),
    CONSTRAINT tarjetas_exp_year_rango CHECK (exp_year BETWEEN 2024 AND 2100)
);

CREATE TABLE pagos (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      INTEGER NOT NULL,
    tarjeta_id      INTEGER NOT NULL,
    monto           NUMERIC(12, 2) NOT NULL,
    currency        VARCHAR(10) NOT NULL DEFAULT 'USD',
    status          VARCHAR(20) NOT NULL,
    motivo_rechazo  TEXT,
    transaction_id  VARCHAR(150),
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pagos_usuario_fkey
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT pagos_tarjeta_usuario_fkey
        FOREIGN KEY (tarjeta_id, usuario_id)
        REFERENCES tarjetas(id, usuario_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT pagos_monto_positivo CHECK (monto > 0),
    CONSTRAINT pagos_currency_permitida CHECK (currency IN ('USD', 'EUR', 'MXN', 'COP')),
    CONSTRAINT pagos_status_permitido CHECK (status IN ('approved', 'rejected')),
    CONSTRAINT pagos_rechazo_coherente CHECK (
        (status = 'approved' AND motivo_rechazo IS NULL)
        OR
        (status = 'rejected' AND motivo_rechazo IS NOT NULL AND btrim(motivo_rechazo) <> '')
    ),
    CONSTRAINT pagos_transaction_id_unique UNIQUE (transaction_id)
);

-- PostgreSQL no crea índices automáticamente para las columnas que referencian
-- claves foráneas. Estos índices cubren las consultas actuales de la API.
CREATE INDEX idx_tarjetas_usuario ON tarjetas (usuario_id);
CREATE UNIQUE INDEX idx_tarjetas_token_unique
    ON tarjetas (token) WHERE token IS NOT NULL;
CREATE INDEX idx_pagos_usuario_fecha
    ON pagos (usuario_id, creado_en DESC);
CREATE INDEX idx_pagos_tarjeta ON pagos (tarjeta_id);

-- Datos de demostración. Son idempotentes gracias a sus claves naturales y no
-- forman parte de la estructura requerida por la aplicación.
INSERT INTO usuarios (nombre, email, telefono, direccion)
VALUES
    ('Juan Pérez', 'juan.perez@example.com', '+34123456789', 'Calle Falsa 123'),
    ('María García', 'maria.garcia@example.com', '+34987654321', 'Avenida Siempre Viva 742')
ON CONFLICT (email) DO NOTHING;

INSERT INTO tarjetas (usuario_id, alias, brand, last4, exp_month, exp_year, token)
SELECT id, 'Visa personal', 'Visa', '4242', 12, 2030, 'tok_visa_demo_1'
FROM usuarios WHERE email = 'juan.perez@example.com'
ON CONFLICT (token) WHERE token IS NOT NULL DO NOTHING;

INSERT INTO tarjetas (usuario_id, alias, brand, last4, exp_month, exp_year, token)
SELECT id, 'Mastercard empresa', 'Mastercard', '5555', 11, 2031, 'tok_mc_demo_1'
FROM usuarios WHERE email = 'juan.perez@example.com'
ON CONFLICT (token) WHERE token IS NOT NULL DO NOTHING;

INSERT INTO tarjetas (usuario_id, alias, brand, last4, exp_month, exp_year, token)
SELECT id, 'Visa prueba', 'Visa', '4000', 1, 2032, 'tok_visa_demo_2'
FROM usuarios WHERE email = 'maria.garcia@example.com'
ON CONFLICT (token) WHERE token IS NOT NULL DO NOTHING;

INSERT INTO pagos (
    usuario_id, tarjeta_id, monto, currency, status, motivo_rechazo, transaction_id
)
SELECT u.id, t.id, 50.00, 'USD', 'approved', NULL, 'TXN_DEMO_100001'
FROM usuarios u
JOIN tarjetas t ON t.usuario_id = u.id AND t.token = 'tok_visa_demo_1'
WHERE u.email = 'juan.perez@example.com'
ON CONFLICT (transaction_id) DO NOTHING;

INSERT INTO pagos (
    usuario_id, tarjeta_id, monto, currency, status, motivo_rechazo, transaction_id
)
SELECT u.id, t.id, 125.00, 'EUR', 'rejected', 'Fondos insuficientes', 'TXN_DEMO_100002'
FROM usuarios u
JOIN tarjetas t ON t.usuario_id = u.id AND t.token = 'tok_mc_demo_1'
WHERE u.email = 'juan.perez@example.com'
ON CONFLICT (transaction_id) DO NOTHING;

INSERT INTO pagos (
    usuario_id, tarjeta_id, monto, currency, status, motivo_rechazo, transaction_id
)
SELECT u.id, t.id, 10.00, 'USD', 'approved', NULL, 'TXN_DEMO_100003'
FROM usuarios u
JOIN tarjetas t ON t.usuario_id = u.id AND t.token = 'tok_visa_demo_2'
WHERE u.email = 'maria.garcia@example.com'
ON CONFLICT (transaction_id) DO NOTHING;

COMMIT;
